all:
	convert Translatron-NER.jpg Translatron-NER.eps
	convert Translatron-Entity.jpg Translatron-Entity.eps
	convert Translatron-Search.jpg Translatron-Search.eps
	convert Translatron-Wikipedia.jpg Translatron-Wikipedia.eps
	convert Translatron-Nuclease.jpg Translatron-Nuclease.eps
